#!/bin/bash
# Generate self-signed certificate for HTTPS server
# This creates a certificate valid for local mDNS hostnames

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CERT_DIR="$PROJECT_ROOT/certs"
SRC_FILE="$PROJECT_ROOT/src/https_cert.c"

echo "Generating self-signed certificate for HID Proxy HTTPS server..."

# Create certs directory
mkdir -p "$CERT_DIR"

# Generate private key (RSA 2048-bit)
openssl genrsa -out "$CERT_DIR/server.key" 2048

# Create certificate configuration file
cat > "$CERT_DIR/cert.conf" <<EOF
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = hidproxy.local

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = hidproxy.local
DNS.2 = hidproxy-*.local
DNS.3 = *.local
DNS.4 = localhost
IP.1 = 192.168.0.0/16
IP.2 = 10.0.0.0/8
IP.3 = 172.16.0.0/12
EOF

# Generate self-signed certificate (valid for 10 years)
openssl req -new -x509 -key "$CERT_DIR/server.key" \
    -out "$CERT_DIR/server.crt" \
    -days 3650 \
    -config "$CERT_DIR/cert.conf"

echo "Certificate generated:"
echo "  Private key: $CERT_DIR/server.key"
echo "  Certificate: $CERT_DIR/server.crt"

# Convert to C source file
echo "Converting to C source file..."

cat > "$SRC_FILE" <<'EOF'
#include "https_cert.h"

// Self-signed certificate for HTTPS server
// Generated by tools/generate_cert.sh
// Valid for hidproxy*.local and localhost
// Note: Browsers will show security warning for self-signed certificates

EOF

# Add certificate
echo "const unsigned char server_cert_pem[] =" >> "$SRC_FILE"
sed 's/.*/"&\\n"/' "$CERT_DIR/server.crt" >> "$SRC_FILE"
echo ';' >> "$SRC_FILE"
echo "" >> "$SRC_FILE"
echo "const size_t server_cert_pem_len = sizeof(server_cert_pem);" >> "$SRC_FILE"
echo "" >> "$SRC_FILE"

# Add private key
echo "const unsigned char server_key_pem[] =" >> "$SRC_FILE"
sed 's/.*/"&\\n"/' "$CERT_DIR/server.key" >> "$SRC_FILE"
echo ';' >> "$SRC_FILE"
echo "" >> "$SRC_FILE"
echo "const size_t server_key_pem_len = sizeof(server_key_pem);" >> "$SRC_FILE"

echo "✓ C source file updated: $SRC_FILE"
echo ""
echo "Certificate information:"
openssl x509 -in "$CERT_DIR/server.crt" -text -noout | grep -A2 "Subject:"
echo ""
echo "Note: You must rebuild the firmware for changes to take effect"
